name: Sync Fork
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream
        run: gh repo sync ${{ github.repository }} --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}